### ISSUE TITLE
Wrong example code for checking folder's items

### ISSUE THREAD

**Issue by tehn-r** [box/box-salesforce-sdk#12]
You don't have an access to **getObjectType()** method from BoxItem.Info instance.
This code will not work: https://github.com/box/box-salesforce-sdk/blob/master/doc/folders.md#get-a-folders-items

**Comment by shinsaka** [comment]
It works by changing `itemInfo.type` insted of `itemInfo.getObjectType()`.
However, I assume different from programmer's intended.

Probably, they wants to implement `abstract String getObjectType()` into `BoxResource.Info class`.

**Comment by tehn-r** [comment]
Sure, I used that approach, but for newcomers it is better to have a valid example or integrated getObjectType() mehod.
