### ISSUE TITLE
I just cannot believe how poorly coded this SDK is. Lot's of bugs!!!

### ISSUE THREAD

**Issue by OlegForce** [box/box-salesforce-sdk#13]
This is super bad!

**Comment by OlegForce** [comment]
I was one of the unlucky ones to install the unmanaged package you folks provided in the documentation. Box Apex SDK 1.0 

After looking at the code in this repo, looks like the ones I found have been patched up. Pretty frustrating I had to waste all that time...

**Comment by OlegForce** [comment]
Additionally - what is the deal with custom JSON parser and swallowing of the exception messages (throwing useless custom messages instead)

**Comment by bassman531** [comment]
Closing due to this not being a specific technical issue.  If you want to discuss what problems you ran into, please email us at oss@box.com and we can chat about what went wrong and how we can fix it for other people in the future.

**Comment by OlegForce** [comment]
Emailed :)
