### ISSUE TITLE
getChildren for the folder doesn't work

### ISSUE THREAD

**Issue by AlexTretRealtyShares** [box/box-salesforce-sdk#14]
list<BoxItem.Info> children = folder.getChildren();

throws an exception

BoxJsonObject.BoxJsonObjectException: Json string passed to BoxJsonObject.parseJsonObjectArray was not valid json

**Comment by m-akashi** [comment]
Are You installed from Package Link ?
I also it got an error.

I was able to get the success the latest source code.

**Comment by AlexTretRealtyShares** [comment]
@m-akashi how did you deploy it? did you manually copy over all files?

**Comment by m-akashi** [comment]
I use Force.com IDE with eclipse.
You might want to create a unmanaged package in the Salesforce Developer Edition.

**Comment by AlexTretRealtyShares** [comment]
@m-akashi Thnx for the reply, I was able to resolve the issue by pulling down the latest version of the code and deploying to sandbox using Ant. Package link doesn't seem to have the latest version of the code.

**Comment by bassman531** [comment]
The install link has been updated and documentation around merging commits now includes updating that package link for Box employees doing the push.
