### ISSUE TITLE
Cannot obtain user token based on the enterprise configuration for your app

### ISSUE THREAD

**Issue by OlegForce** [box/box-salesforce-sdk#17]
I am using the JWT auth and not able to connect with the app user after creating one through enterprise connection. `  BoxJwtEncryptionPreferences preferences = new BoxJwtEncryptionPreferences();
            preferences.setPublicKeyId(publicKeyId);
            preferences.setPrivateKey(privateKey);
           
           BoxPlatformApiConnection pApi = BoxPlatformApiConnection.getAppEnterpriseConnection(userId, clientId, clientSecret, preferences);

 ```BoxApiConnection api = new BoxApiConnection (pApi.getAccessToken()); //create api instance```
	
	BoxUser.createAppUser (api, 'appUser2');
`
This one successfully gives me the token and creates a user for the app. 

After that one I am trying to getappuserconnection but getting error. What am I missing? My app is configured to work with app users. 

`BoxPlatformApiConnection pApi = BoxPlatformApiConnection.getAppUserConnection(userId, clientId, clientSecret, preferences);
`

**Comment by bassman531** [comment]
This is a known issue on our end right now and is not specific to any SDK.  The same issue was reported against our [Java SDK](https://github.com/box/box-java-sdk/issues/268).  I will update this issue thread once we have a resolution.

**Comment by OlegForce** [comment]
Thanks @bassman531 . Do you have an ETA of the fix or any workaround?

**Comment by tarrencev** [comment]
@OlegForce this issue should be resolved now, sorry for the inconvenience

**Comment by OlegForce** [comment]
Great :) Thank you!

**Comment by mlugert** [comment]
As of January 27, 2017 I'm seeing this exact same thing using the Java SDK, using this branch:  box-java-sdk-2.2.3-SNAPSHOT
