### ISSUE TITLE
Sandbox Package Link in Repo readme is out of date.

### ISSUE THREAD

**Issue by jclark-dot-org** [box/box-salesforce-sdk#18]
Ran into an issue where getting the current User failed with "Invalid long: 1.0e+15"; the stack trace and inspection of the raw response show that the raw JSON response includes:

    "space_amount":1.0e+15

which BoxUser.Info is trying to parse as a long(); Apex's long.valueOf(x) method cannot parse scientific notation.

Looks like commit c4b5287 addressed that issue for a space_amount number of other fields back in March; I just installed the SDK today using the "Sandbox Package Link" in the readme, and didn't get that fix.  Not sure how to tell how old the installed code is, but it isn't current.

**Comment by bassman531** [comment]
fixed the external link
