### ISSUE TITLE
Custom object usage limits

### ISSUE THREAD

**Issue by codebank** [box/box-salesforce-sdk#3]
Exposing Box content within 1 or more custom objects in Salesforce may have serious consequences for clients API usage limits. We believe the architecture of this system poses unique challenges for developers, administrators and for Salesforce operations team to track API utilization. 

We propose an enhancement which would audit the number updates made to Salesforce Custom Objects and audit the clients usage limit associated with the Salesforce instance. This data would be visible on granular level for analysis. This data could be useful to correlate the changes in the target instance for verifying more complex work flows.

**Comment by bassman531** [comment]
@codebank 
What exactly are you suggesting be added to the SDK?  There are no updates to custom or standard objects in the SDK.  Are you suggesting a programmatic way to see the number of API calls that have been executed in the current execution context?  If so, how is that better than just calling Limits.getCallouts()?

Org-wide 24 hour callout limits are significant enough that it's probably not worth adding aggregate logging for tracking.
