### ISSUE TITLE
Issue installing

### ISSUE THREAD

**Issue by bglasco** [box/box-salesforce-sdk#34]
Failures:
classes/BoxApiConnection.cls(69,37):Dependent class is invalid and needs recompilation:
Class.BoxApiRequest.getBoxResourceResponseBody: line 205, column 23
BoxResource: line 36, column 36: Dependent class is invalid and needs recompilation:
BoxFolder: line 341, column 12: Invalid type: BoxFile.Info
classes/BoxApiConnectionTests.cls(11,37):Dependent class is invalid and needs recompilation:
Class.BoxApiConnection.authenticate: line 69, column 37

**Comment by akhanna02** [comment]
Any update on this issue? I am having the problem.
