### ISSUE TITLE
Compilation issues

### ISSUE THREAD

**Issue by joshkraszeski** [box/box-salesforce-sdk#37]
- Line 228 in BoxFileTests does not compile
- Line 263 in BoxFile does not compile
	- ensureBoxResourceResponseBody does not exist
	- Changed to getBoxResourceResponseBody
- Line 354 invalid public declaration

**Comment by cburnette** [comment]
@carycheng77 Hey Cary, can you take a look at this?  This is from a company called nCino that is trying to user this SDK but ran into some compilation errors.

**Comment by drewcparker** [comment]
Thanks for bringing this up... this has been fixed now 😃
